import type { AiResponseProps } from "@/lib/props";
import {
  AlertDialog,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import { api } from "@/lib/api";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { SpinnerCustom } from "./ui/spinner";

export default function AiResponse({
  responseOpen,
  onOpenChange,
  job,
}: AiResponseProps) {
  const [isLoading, setIsLoading] = useState(false);
  const [response, setResponse] = useState<string>("");

  useEffect(() => {
    if (!responseOpen) return;
    let cancelled = false;
    const fetchResponse = async () => {
      setIsLoading(true);
      try {
        const res = await api.post("/openrouter/ask", { job });
        if (!cancelled) {
          setResponse(res.data.response);
        }
      } catch (error) {
        if (!cancelled) {
          toast.error("Failed to fetch AI response.");
          console.error(error);
        }
      } finally {
        if (!cancelled) {
          setIsLoading(false);
        }
      }
    };
    fetchResponse();
    return () => {
      cancelled = true;
    };
  }, [responseOpen, job]);

  return (
    <AlertDialog open={responseOpen} onOpenChange={onOpenChange}>
      <AlertDialogContent className="max-h-[80vh] overflow-hidden">
        <AlertDialogHeader>
          <AlertDialogTitle>AI Analysis Report</AlertDialogTitle>
          <AlertDialogDescription>
            View the detailed analysis generated by the AI based on the job
            information provided.
          </AlertDialogDescription>
        </AlertDialogHeader>
        <div className="max-h-[50vh] overflow-y-auto scrollbar-hide pr-2">
          {isLoading ? <SpinnerCustom /> : response}
        </div>
        <AlertDialogFooter>
          <AlertDialogCancel>Close</AlertDialogCancel>
        </AlertDialogFooter>
      </AlertDialogContent>
    </AlertDialog>
  );
}
